from contextlib import contextmanager
from datetime import datetime
import os
import sqlite3
from zoneinfo import ZoneInfo

from dotenv import load_dotenv


load_dotenv()

ARQUIVO_BANCO = 'equipamentos.db'
DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
MODO_BANCO = os.getenv('MODO_BANCO', '').strip().lower()
FUSO_HORARIO = ZoneInfo('America/Sao_Paulo')

try:
    import psycopg
    from psycopg.rows import dict_row

except ImportError:
    psycopg = None
    dict_row = None


ERROS_INTEGRIDADE = (sqlite3.IntegrityError,)

if psycopg is not None:
    ERROS_INTEGRIDADE += (psycopg.IntegrityError,)


def usa_postgres():
    return MODO_BANCO != 'sqlite' and bool(DATABASE_URL)


def usa_sqlite():
    return not usa_postgres()


def nome_backend():
    return 'PostgreSQL/Supabase' if usa_postgres() else 'SQLite local'


@contextmanager
def conectar():
    if usa_postgres():
        if psycopg is None:
            raise RuntimeError(
                'Instale as dependências com: '
                'python -m pip install -r requirements.txt'
            )

        conexao = psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row,
            prepare_threshold=None
        )

    else:
        conexao = sqlite3.connect(ARQUIVO_BANCO)
        conexao.row_factory = sqlite3.Row

    try:
        yield conexao
        conexao.commit()

    except Exception:
        conexao.rollback()
        raise

    finally:
        conexao.close()


def _data_para_postgres(valor):
    if isinstance(valor, datetime):
        if valor.tzinfo is None:
            return valor.replace(tzinfo=FUSO_HORARIO)
        return valor

    try:
        data = datetime.strptime(str(valor), '%d/%m/%Y %H:%M')
        return data.replace(tzinfo=FUSO_HORARIO)

    except (TypeError, ValueError):
        return None


def _formatar_data(valor):
    if not isinstance(valor, datetime):
        return valor

    if valor.tzinfo is not None:
        valor = valor.astimezone(FUSO_HORARIO)

    return valor.strftime('%d/%m/%Y %H:%M')


def _equipamento_para_dict(registro):
    equipamento = dict(registro)
    equipamento['data_cadastro'] = _formatar_data(
        equipamento.get('data_cadastro')
    )
    equipamento['ultima_atualizacao'] = _formatar_data(
        equipamento.get('ultima_atualizacao')
    )
    return equipamento


def criar_tabela():
    if usa_postgres():
        sql_equipamentos = '''
            CREATE TABLE IF NOT EXISTS public.equipamentos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                patrimonio TEXT NOT NULL UNIQUE,
                serial TEXT NOT NULL UNIQUE,
                categoria TEXT NOT NULL,
                setor TEXT NOT NULL DEFAULT 'Não informado',
                responsavel TEXT NOT NULL DEFAULT 'Não informado',
                status TEXT NOT NULL CHECK (
                    status IN (
                        'Em uso',
                        'Disponível',
                        'Em manutenção',
                        'Baixado'
                    )
                ),
                data_cadastro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                ultima_atualizacao TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        '''
        sql_configuracoes = '''
            CREATE TABLE IF NOT EXISTS public.configuracoes (
                chave TEXT PRIMARY KEY,
                valor TEXT NOT NULL
            )
        '''

    else:
        sql_equipamentos = '''
            CREATE TABLE IF NOT EXISTS equipamentos (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nome TEXT NOT NULL,
                patrimonio TEXT NOT NULL UNIQUE,
                serial TEXT NOT NULL UNIQUE,
                categoria TEXT NOT NULL,
                setor TEXT NOT NULL,
                responsavel TEXT NOT NULL,
                status TEXT NOT NULL,
                data_cadastro TEXT NOT NULL,
                ultima_atualizacao TEXT NOT NULL
            )
        '''
        sql_configuracoes = '''
            CREATE TABLE IF NOT EXISTS configuracoes (
                chave TEXT PRIMARY KEY,
                valor TEXT NOT NULL
            )
        '''

    with conectar() as conexao:
        conexao.execute(sql_equipamentos)
        conexao.execute(sql_configuracoes)


def inserir_equipamento(equipamento):
    valores = (
        equipamento['nome'],
        equipamento['patrimonio'],
        equipamento['serial'],
        equipamento['categoria'],
        equipamento['setor'],
        equipamento['responsavel'],
        equipamento['status']
    )

    if usa_postgres():
        sql = '''
            INSERT INTO public.equipamentos (
                nome,
                patrimonio,
                serial,
                categoria,
                setor,
                responsavel,
                status,
                data_cadastro,
                ultima_atualizacao
            )
            VALUES (
                %s, %s, %s, %s, %s, %s, %s,
                COALESCE(%s, CURRENT_TIMESTAMP),
                COALESCE(%s, CURRENT_TIMESTAMP)
            )
            RETURNING id
        '''
        valores += (
            _data_para_postgres(equipamento.get('data_cadastro')),
            _data_para_postgres(equipamento.get('ultima_atualizacao'))
        )

    else:
        sql = '''
            INSERT INTO equipamentos (
                nome,
                patrimonio,
                serial,
                categoria,
                setor,
                responsavel,
                status,
                data_cadastro,
                ultima_atualizacao
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        '''
        valores += (
            equipamento['data_cadastro'],
            equipamento['ultima_atualizacao']
        )

    with conectar() as conexao:
        cursor = conexao.execute(sql, valores)

        if usa_postgres():
            return cursor.fetchone()['id']

        return cursor.lastrowid


def listar_equipamentos():
    tabela = 'public.equipamentos' if usa_postgres() else 'equipamentos'

    with conectar() as conexao:
        resultados = conexao.execute(
            f'SELECT * FROM {tabela} ORDER BY id'
        ).fetchall()

    return [_equipamento_para_dict(registro) for registro in resultados]


def buscar_equipamento_por_id(equipamento_id):
    if usa_postgres():
        sql = 'SELECT * FROM public.equipamentos WHERE id = %s'
    else:
        sql = 'SELECT * FROM equipamentos WHERE id = ?'

    with conectar() as conexao:
        resultado = conexao.execute(sql, (equipamento_id,)).fetchone()

    if resultado is None:
        return None

    return _equipamento_para_dict(resultado)


def atualizar_equipamento(equipamento):
    if usa_postgres():
        sql = '''
            UPDATE public.equipamentos
            SET
                nome = %s,
                patrimonio = %s,
                serial = %s,
                categoria = %s,
                setor = %s,
                responsavel = %s,
                status = %s,
                data_cadastro = COALESCE(%s, data_cadastro),
                ultima_atualizacao = COALESCE(%s, CURRENT_TIMESTAMP)
            WHERE id = %s
        '''
        datas = (
            _data_para_postgres(equipamento.get('data_cadastro')),
            _data_para_postgres(equipamento.get('ultima_atualizacao'))
        )

    else:
        sql = '''
            UPDATE equipamentos
            SET
                nome = ?,
                patrimonio = ?,
                serial = ?,
                categoria = ?,
                setor = ?,
                responsavel = ?,
                status = ?,
                data_cadastro = ?,
                ultima_atualizacao = ?
            WHERE id = ?
        '''
        datas = (
            equipamento['data_cadastro'],
            equipamento['ultima_atualizacao']
        )

    valores = (
        equipamento['nome'],
        equipamento['patrimonio'],
        equipamento['serial'],
        equipamento['categoria'],
        equipamento['setor'],
        equipamento['responsavel'],
        equipamento['status'],
        *datas,
        equipamento['id']
    )

    with conectar() as conexao:
        cursor = conexao.execute(sql, valores)

    return cursor.rowcount > 0


def remover_equipamento(equipamento_id):
    if usa_postgres():
        sql = 'DELETE FROM public.equipamentos WHERE id = %s'
    else:
        sql = 'DELETE FROM equipamentos WHERE id = ?'

    with conectar() as conexao:
        cursor = conexao.execute(sql, (equipamento_id,))

    return cursor.rowcount > 0


def migracao_json_concluida():
    tabela = 'public.configuracoes' if usa_postgres() else 'configuracoes'
    marcador = '%s' if usa_postgres() else '?'

    with conectar() as conexao:
        resultado = conexao.execute(
            f'SELECT valor FROM {tabela} WHERE chave = {marcador}',
            ('json_migrado',)
        ).fetchone()

    return resultado is not None and resultado['valor'] == 'sim'


def marcar_migracao_json():
    if usa_postgres():
        sql = '''
            INSERT INTO public.configuracoes (chave, valor)
            VALUES (%s, %s)
            ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor
        '''
    else:
        sql = '''
            INSERT OR REPLACE INTO configuracoes (chave, valor)
            VALUES (?, ?)
        '''

    with conectar() as conexao:
        conexao.execute(sql, ('json_migrado', 'sim'))
