from contextlib import contextmanager
from datetime import datetime
import json
import os
import sqlite3
from zoneinfo import ZoneInfo

from dotenv import load_dotenv


load_dotenv()

ARQUIVO_BANCO = 'equipamentos.db'
DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
MODO_BANCO = os.getenv('MODO_BANCO', '').strip().lower()
FUSO_HORARIO = ZoneInfo('America/Sao_Paulo')

try:
    import psycopg
    from psycopg.rows import dict_row

except ImportError:
    psycopg = None
    dict_row = None


ERROS_INTEGRIDADE = (sqlite3.IntegrityError,)

if psycopg is not None:
    ERROS_INTEGRIDADE += (psycopg.IntegrityError,)


def usa_postgres():
    return MODO_BANCO != 'sqlite' and bool(DATABASE_URL)


def usa_sqlite():
    return not usa_postgres()


def nome_backend():
    return 'PostgreSQL/Supabase' if usa_postgres() else 'SQLite local'


@contextmanager
def conectar():
    if usa_postgres():
        if psycopg is None:
            raise RuntimeError(
                'Instale as dependências com: '
                'python -m pip install -r requirements.txt'
            )

        conexao = psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row,
            prepare_threshold=None
        )

    else:
        conexao = sqlite3.connect(ARQUIVO_BANCO)
        conexao.row_factory = sqlite3.Row

    try:
        yield conexao
        conexao.commit()

    except Exception:
        conexao.rollback()
        raise

    finally:
        conexao.close()


def _data_para_postgres(valor):
    if isinstance(valor, datetime):
        if valor.tzinfo is None:
            return valor.replace(tzinfo=FUSO_HORARIO)
        return valor

    try:
        data = datetime.strptime(str(valor), '%d/%m/%Y %H:%M')
        return data.replace(tzinfo=FUSO_HORARIO)

    except (TypeError, ValueError):
        return None


def _formatar_data(valor):
    if not isinstance(valor, datetime):
        return valor

    if valor.tzinfo is not None:
        valor = valor.astimezone(FUSO_HORARIO)

    return valor.strftime('%d/%m/%Y %H:%M')


def _equipamento_para_dict(registro):
    equipamento = dict(registro)
    equipamento['data_cadastro'] = _formatar_data(
        equipamento.get('data_cadastro')
    )
    equipamento['ultima_atualizacao'] = _formatar_data(
        equipamento.get('ultima_atualizacao')
    )
    return equipamento


def criar_tabela():
    if usa_postgres():
        sql_equipamentos = '''
            CREATE TABLE IF NOT EXISTS public.equipamentos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                patrimonio TEXT NOT NULL UNIQUE,
                serial TEXT NOT NULL UNIQUE,
                categoria TEXT NOT NULL,
                setor TEXT NOT NULL DEFAULT 'Não informado',
                responsavel TEXT NOT NULL DEFAULT 'Não informado',
                status TEXT NOT NULL CHECK (
                    status IN (
                        'Em uso',
                        'Disponível',
                        'Em manutenção',
                        'Baixado'
                    )
                ),
                data_cadastro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                ultima_atualizacao TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        '''
        sql_configuracoes = '''
            CREATE TABLE IF NOT EXISTS public.configuracoes (
                chave TEXT PRIMARY KEY,
                valor TEXT NOT NULL
            )
        '''
        sql_usuarios = '''
            CREATE TABLE IF NOT EXISTS public.usuarios (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                senha_hash TEXT NOT NULL,
                perfil TEXT NOT NULL CHECK (
                    perfil IN ('administrador', 'operador', 'consulta')
                ),
                ativo BOOLEAN NOT NULL DEFAULT TRUE,
                criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        '''
        sql_historico = '''
            CREATE TABLE IF NOT EXISTS public.historico (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                equipamento_id BIGINT,
                usuario_id BIGINT,
                usuario_nome TEXT NOT NULL,
                acao TEXT NOT NULL,
                detalhes TEXT NOT NULL,
                data_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        '''

    else:
        sql_equipamentos = '''
            CREATE TABLE IF NOT EXISTS equipamentos (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nome TEXT NOT NULL,
                patrimonio TEXT NOT NULL UNIQUE,
                serial TEXT NOT NULL UNIQUE,
                categoria TEXT NOT NULL,
                setor TEXT NOT NULL,
                responsavel TEXT NOT NULL,
                status TEXT NOT NULL,
                data_cadastro TEXT NOT NULL,
                ultima_atualizacao TEXT NOT NULL
            )
        '''
        sql_configuracoes = '''
            CREATE TABLE IF NOT EXISTS configuracoes (
                chave TEXT PRIMARY KEY,
                valor TEXT NOT NULL
            )
        '''
        sql_usuarios = '''
            CREATE TABLE IF NOT EXISTS usuarios (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nome TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                senha_hash TEXT NOT NULL,
                perfil TEXT NOT NULL,
                ativo INTEGER NOT NULL DEFAULT 1,
                criado_em TEXT NOT NULL
            )
        '''
        sql_historico = '''
            CREATE TABLE IF NOT EXISTS historico (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                equipamento_id INTEGER,
                usuario_id INTEGER,
                usuario_nome TEXT NOT NULL,
                acao TEXT NOT NULL,
                detalhes TEXT NOT NULL,
                data_hora TEXT NOT NULL
            )
        '''

    with conectar() as conexao:
        conexao.execute(sql_equipamentos)
        conexao.execute(sql_configuracoes)
        conexao.execute(sql_usuarios)
        conexao.execute(sql_historico)


def inserir_equipamento(equipamento):
    valores = (
        equipamento['nome'],
        equipamento['patrimonio'],
        equipamento['serial'],
        equipamento['categoria'],
        equipamento['setor'],
        equipamento['responsavel'],
        equipamento['status']
    )

    if usa_postgres():
        sql = '''
            INSERT INTO public.equipamentos (
                nome,
                patrimonio,
                serial,
                categoria,
                setor,
                responsavel,
                status,
                data_cadastro,
                ultima_atualizacao
            )
            VALUES (
                %s, %s, %s, %s, %s, %s, %s,
                COALESCE(%s, CURRENT_TIMESTAMP),
                COALESCE(%s, CURRENT_TIMESTAMP)
            )
            RETURNING id
        '''
        valores += (
            _data_para_postgres(equipamento.get('data_cadastro')),
            _data_para_postgres(equipamento.get('ultima_atualizacao'))
        )

    else:
        sql = '''
            INSERT INTO equipamentos (
                nome,
                patrimonio,
                serial,
                categoria,
                setor,
                responsavel,
                status,
                data_cadastro,
                ultima_atualizacao
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        '''
        valores += (
            equipamento['data_cadastro'],
            equipamento['ultima_atualizacao']
        )

    with conectar() as conexao:
        cursor = conexao.execute(sql, valores)

        if usa_postgres():
            return cursor.fetchone()['id']

        return cursor.lastrowid


def listar_equipamentos():
    tabela = 'public.equipamentos' if usa_postgres() else 'equipamentos'

    with conectar() as conexao:
        resultados = conexao.execute(
            f'SELECT * FROM {tabela} ORDER BY id'
        ).fetchall()

    return [_equipamento_para_dict(registro) for registro in resultados]


def buscar_equipamento_por_id(equipamento_id):
    if usa_postgres():
        sql = 'SELECT * FROM public.equipamentos WHERE id = %s'
    else:
        sql = 'SELECT * FROM equipamentos WHERE id = ?'

    with conectar() as conexao:
        resultado = conexao.execute(sql, (equipamento_id,)).fetchone()

    if resultado is None:
        return None

    return _equipamento_para_dict(resultado)


def atualizar_equipamento(equipamento):
    if usa_postgres():
        sql = '''
            UPDATE public.equipamentos
            SET
                nome = %s,
                patrimonio = %s,
                serial = %s,
                categoria = %s,
                setor = %s,
                responsavel = %s,
                status = %s,
                data_cadastro = COALESCE(%s, data_cadastro),
                ultima_atualizacao = COALESCE(%s, CURRENT_TIMESTAMP)
            WHERE id = %s
        '''
        datas = (
            _data_para_postgres(equipamento.get('data_cadastro')),
            _data_para_postgres(equipamento.get('ultima_atualizacao'))
        )

    else:
        sql = '''
            UPDATE equipamentos
            SET
                nome = ?,
                patrimonio = ?,
                serial = ?,
                categoria = ?,
                setor = ?,
                responsavel = ?,
                status = ?,
                data_cadastro = ?,
                ultima_atualizacao = ?
            WHERE id = ?
        '''
        datas = (
            equipamento['data_cadastro'],
            equipamento['ultima_atualizacao']
        )

    valores = (
        equipamento['nome'],
        equipamento['patrimonio'],
        equipamento['serial'],
        equipamento['categoria'],
        equipamento['setor'],
        equipamento['responsavel'],
        equipamento['status'],
        *datas,
        equipamento['id']
    )

    with conectar() as conexao:
        cursor = conexao.execute(sql, valores)

    return cursor.rowcount > 0


def remover_equipamento(equipamento_id):
    if usa_postgres():
        sql = 'DELETE FROM public.equipamentos WHERE id = %s'
    else:
        sql = 'DELETE FROM equipamentos WHERE id = ?'

    with conectar() as conexao:
        cursor = conexao.execute(sql, (equipamento_id,))

    return cursor.rowcount > 0


def migracao_json_concluida():
    tabela = 'public.configuracoes' if usa_postgres() else 'configuracoes'
    marcador = '%s' if usa_postgres() else '?'

    with conectar() as conexao:
        resultado = conexao.execute(
            f'SELECT valor FROM {tabela} WHERE chave = {marcador}',
            ('json_migrado',)
        ).fetchone()

    return resultado is not None and resultado['valor'] == 'sim'


def marcar_migracao_json():
    if usa_postgres():
        sql = '''
            INSERT INTO public.configuracoes (chave, valor)
            VALUES (%s, %s)
            ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor
        '''
    else:
        sql = '''
            INSERT OR REPLACE INTO configuracoes (chave, valor)
            VALUES (?, ?)
        '''

    with conectar() as conexao:
        conexao.execute(sql, ('json_migrado', 'sim'))


def inserir_usuario(usuario):
    if usa_postgres():
        sql = '''
            INSERT INTO public.usuarios (
                nome, email, senha_hash, perfil, ativo
            )
            VALUES (%s, %s, %s, %s, %s)
            RETURNING id
        '''
    else:
        sql = '''
            INSERT INTO usuarios (
                nome, email, senha_hash, perfil, ativo, criado_em
            )
            VALUES (?, ?, ?, ?, ?, ?)
        '''

    valores = (
        usuario['nome'],
        usuario['email'].strip().lower(),
        usuario['senha_hash'],
        usuario['perfil'],
        bool(usuario.get('ativo', True))
    )

    if usa_sqlite():
        valores += (datetime.now().strftime('%d/%m/%Y %H:%M'),)

    with conectar() as conexao:
        cursor = conexao.execute(sql, valores)

        if usa_postgres():
            return cursor.fetchone()['id']

        return cursor.lastrowid


def _usuario_para_dict(registro):
    if registro is None:
        return None

    usuario = dict(registro)
    usuario['ativo'] = bool(usuario['ativo'])
    usuario['criado_em'] = _formatar_data(usuario.get('criado_em'))
    return usuario


def buscar_usuario_por_id(usuario_id):
    tabela = 'public.usuarios' if usa_postgres() else 'usuarios'
    marcador = '%s' if usa_postgres() else '?'

    with conectar() as conexao:
        resultado = conexao.execute(
            f'SELECT * FROM {tabela} WHERE id = {marcador}',
            (usuario_id,)
        ).fetchone()

    return _usuario_para_dict(resultado)


def buscar_usuario_por_email(email):
    tabela = 'public.usuarios' if usa_postgres() else 'usuarios'
    marcador = '%s' if usa_postgres() else '?'

    with conectar() as conexao:
        resultado = conexao.execute(
            f'SELECT * FROM {tabela} WHERE LOWER(email) = {marcador}',
            (email.strip().lower(),)
        ).fetchone()

    return _usuario_para_dict(resultado)


def listar_usuarios():
    tabela = 'public.usuarios' if usa_postgres() else 'usuarios'

    with conectar() as conexao:
        resultados = conexao.execute(
            f'SELECT * FROM {tabela} ORDER BY nome, email'
        ).fetchall()

    return [_usuario_para_dict(registro) for registro in resultados]


def atualizar_usuario(usuario):
    marcador = '%s' if usa_postgres() else '?'
    tabela = 'public.usuarios' if usa_postgres() else 'usuarios'
    sql = f'''
        UPDATE {tabela}
        SET nome = {marcador},
            email = {marcador},
            perfil = {marcador},
            ativo = {marcador}
        WHERE id = {marcador}
    '''
    valores = (
        usuario['nome'],
        usuario['email'].strip().lower(),
        usuario['perfil'],
        bool(usuario['ativo']),
        usuario['id']
    )

    with conectar() as conexao:
        cursor = conexao.execute(sql, valores)

    return cursor.rowcount > 0


def atualizar_senha_usuario(usuario_id, senha_hash):
    marcador = '%s' if usa_postgres() else '?'
    tabela = 'public.usuarios' if usa_postgres() else 'usuarios'

    with conectar() as conexao:
        cursor = conexao.execute(
            f'UPDATE {tabela} SET senha_hash = {marcador} '
            f'WHERE id = {marcador}',
            (senha_hash, usuario_id)
        )

    return cursor.rowcount > 0


def registrar_historico(
    equipamento_id,
    usuario_id,
    usuario_nome,
    acao,
    detalhes
):
    tabela = 'public.historico' if usa_postgres() else 'historico'
    marcador = '%s' if usa_postgres() else '?'
    colunas = (
        'equipamento_id, usuario_id, usuario_nome, '
        'acao, detalhes, data_hora'
    )
    sql = (
        f'INSERT INTO {tabela} ({colunas}) VALUES '
        f'({marcador}, {marcador}, {marcador}, {marcador}, '
        f'{marcador}, {marcador})'
    )
    data_atual = datetime.now(FUSO_HORARIO)
    data_banco = (
        data_atual
        if usa_postgres()
        else data_atual.strftime('%d/%m/%Y %H:%M')
    )

    with conectar() as conexao:
        conexao.execute(
            sql,
            (
                equipamento_id,
                usuario_id,
                usuario_nome,
                acao,
                json.dumps(detalhes, ensure_ascii=False),
                data_banco
            )
        )


def listar_historico(limite=200):
    tabela = 'public.historico' if usa_postgres() else 'historico'
    marcador = '%s' if usa_postgres() else '?'

    with conectar() as conexao:
        resultados = conexao.execute(
            f'SELECT * FROM {tabela} ORDER BY id DESC LIMIT {marcador}',
            (limite,)
        ).fetchall()

    historico = []

    for registro in resultados:
        item = dict(registro)
        item['data_hora'] = _formatar_data(item.get('data_hora'))

        try:
            item['detalhes'] = json.loads(item['detalhes'])
        except (TypeError, json.JSONDecodeError):
            item['detalhes'] = {}

        historico.append(item)

    return historico
